
import path from "path"
export default {
    mode: 'production',
    devtool: false,
    entry: {
        menu: './src/js/menus.js',
        textoLista: './src/js/textoLista.js',
        dataAsync: './src/js/dataAsync.js',
        dropdownBtn: './src/js/dropdownBtn',
        steepForms: './src/js/steepForms.js',
        productDataForm: '/src/js/productDataForm.js',
        editorMetaDescripcion: '/src/js/editorMetaDescripcion.js',
        productList: '/src/js/productList.js',
        paginador: '/src/js/paginador.js',
        helpers: '/src/js/helpers.js',
        dataStore: '/src/js/dataStore.js',
        dataSupplier: '/src/js/dataSupplier.js',
        supplierList: '/src/js/supplierList.js',
        dataDose : '/src/js/dataDose.js',
        utils : '/src/js/utils.js',
        dosificador : '/src/js/dosificador.js',
        listadoDose : '/src/js/listadoDose.js',
        doseView : '/src/js/doseView.js',
        dataEmployee : '/src/js/dataEmployee.js',
        employeeList : '/src/js/employeeList.js',
        pos : '/src/js/pos.js',
        storeGlobal : '/src/js/storeGlobal.js',
        storeTraslados : '/src/js/storeTraslados.js',
        storeInventario : '/src/js/storeInventario.js',
        storeEgresos : '/src/js/storeEgresos.js',
        adminTiendasLive    : '/src/js/adminTiendasLive.js',
        adminStoreStats     : '/src/js/adminStoreStats.js',
        adminStoreBilling   : '/src/js/adminStoreBilling.js',
        storeCuadrarCaja    : '/src/js/storeCuadrarCaja.js',
        storeSales          : '/src/js/storeSales.js',
        adminProductoView   : '/src/js/adminProductoView.js',
        adminDashboard      : '/src/js/adminDashboard.js',
        adminClientes       : '/src/js/adminClientes.js',
        dataCliente         : '/src/js/dataCliente.js',
        batchOrder          : '/src/js/batchOrder.js',
        adminCierresCaja    : '/src/js/adminCierresCaja.js',
        adminTrasladosTienda: '/src/js/adminTrasladosTienda.js',
        adminDocsTienda     : '/src/js/adminDocsTienda.js',
        adminPedidosWeb     : '/src/js/adminPedidosWeb.js',
        adminPedidoDetalle  : '/src/js/adminPedidoDetalle.js',
        storePedidosWeb     : '/src/js/storePedidosWeb.js',
        adminAlertas        : '/src/js/adminAlertas.js'
    },
    output: {
        filename: '[name].js',
        path: path.resolve('public/js/')

    }
}