 const nombresData = [
{ tipo: 'COLOR', codigo1: '#000000', valor: 'Negro' },
{ tipo: 'COLOR', codigo1: '#FFFFFF', valor: 'Blanco' },
{ tipo: 'COLOR', codigo1: '#FFC0CB', valor: 'Rosa' },
{ tipo: 'COLOR', codigo1: '#C8A2C8', valor: 'Lila' },
{ tipo: 'COLOR', codigo1: '#F5F5DC', valor: 'Beige' },
{ tipo: 'COLOR', codigo1: '#9FB6CD', valor: 'Azul Hortensia' },
{ tipo: 'COLOR', codigo1: '#002366', valor: 'Azul Rey' },
{ tipo: 'COLOR', codigo1: '#7B3F00', valor: 'Chocolate' },
{ tipo: 'COLOR', codigo1: '#EFDECD', valor: 'Almendra' },
{ tipo: 'COLOR', codigo1: '#C19A6B', valor: 'Camel' },
{ tipo: 'COLOR', codigo1: '#009739', valor: 'Verde Brasil' },
{ tipo: 'COLOR', codigo1: '#006A4E', valor: 'Verde Botella' },
{ tipo: 'COLOR', codigo1: '#7FFFD4', valor: 'Verde Aguamarina' },
{ tipo: 'COLOR', codigo1: '#820000', valor: 'Vinotinto' },
{ tipo: 'COLOR', codigo1: '#FF0000', valor: 'Rojo' },
{ tipo: 'COLOR', codigo1: '#D68A8A', valor: 'Palo Rosa' },
{ tipo: 'COLOR', codigo1: '#6B8E23', valor: 'Verde Seco' },
{ tipo: 'COLOR', codigo1: '#D3D3D3', valor: 'Gris Jaspeado' },
{ tipo: 'COLOR', codigo1: '#E5D5B7', valor: 'Beige Jaspeado' },
{ tipo: 'COLOR', codigo1: '#FFF9B1', valor: 'Amarillo Pastel' },
{ tipo: 'COLOR', codigo1: '#4B5320', valor: 'Verde Militar' },
{ tipo: 'COLOR', codigo1: '#DA1884', valor: 'Barbie' },
{ tipo: 'COLOR', codigo1: '#CCFF00', valor: 'Amarillo Neón' },
{ tipo: 'COLOR', codigo1: '#39FF14', valor: 'Verde Neón' },
{ tipo: 'COLOR', codigo1: '#800080', valor: 'Morado' },
{ tipo: 'COLOR', codigo1: '#FCD116', valor: 'Amarillo Colombia' },
{ tipo: 'COLOR', codigo1: '#FF8C00', valor: 'Naranja' },
{ tipo: 'COLOR', codigo1: '#FEBAAD', valor: 'Melón' },
{ tipo: 'COLOR', codigo1: '#4B3621', valor: 'Café' },
{ tipo: 'COLOR', codigo1: '#FF00FF', valor: 'Fucsia' },
{ tipo: 'COLOR', codigo1: '#FFFFFF', codigo2: '#000000', valor: 'Blanco + Negro' },
{ tipo: 'COLOR', codigo1: '#000000', codigo2: '#FFFFFF', valor: 'Negro + Blanco' },
{ tipo: 'COLOR', codigo1: '#C8A2C8', codigo2: '#FFFFFF', valor: 'Lila + Blanco' },
{ tipo: 'COLOR', codigo1: '#FFFFFF', codigo2: '#C8A2C8', valor: 'Blanco + Lila' },
{ tipo: 'COLOR', codigo1: '#FFC0CB', codigo2: '#FFFFFF', valor: 'Rosa + Blanco' },
{ tipo: 'COLOR', codigo1: '#FFFFFF', codigo2: '#FFC0CB', valor: 'Blanco + Rosa' },
{ tipo: 'COLOR', codigo1: '#9FB6CD', codigo2: '#FFFFFF', valor: 'Azul Hortensia + Blanco' },
{ tipo: 'COLOR', codigo1: '#FFFFFF', codigo2: '#9FB6CD', valor: 'Blanco + Azul Hortensia' },
{ tipo: 'COLOR', codigo1: '#FFFFFF', codigo2: '#002366', valor: 'Blanco + Azul Rey' },
{ tipo: 'COLOR', codigo1: '#002366', codigo2: '#FFFFFF', valor: 'Azul Rey + Blanco' },
{ tipo: 'COLOR', codigo1: '#FFFFFF', codigo2: '#7B3F00', valor: 'Blanco + Chocolate' },
{ tipo: 'COLOR', codigo1: '#7B3F00', codigo2: '#FFFFFF', valor: 'Chocolate + Blanco' },
{ tipo: 'COLOR', codigo1: '#FFFFFF', codigo2: '#EFDECD', valor: 'Blanco + Almendra' },
{ tipo: 'COLOR', codigo1: '#EFDECD', codigo2: '#FFFFFF', valor: 'Almendra + Blanco' },
{ tipo: 'COLOR', codigo1: '#FFFFFF', codigo2: '#C19A6B', valor: 'Blanco + Camel' },
{ tipo: 'COLOR', codigo1: '#C19A6B', codigo2: '#FFFFFF', valor: 'Camel + Blanco' },
{ tipo: 'COLOR', codigo1: '#FFFFFF', codigo2: '#006A4E', valor: 'Blanco + Verde Botella' },
{ tipo: 'COLOR', codigo1: '#006A4E', codigo2: '#FFFFFF', valor: 'Verde Botella + Blanco' },
{ tipo: 'COLOR', codigo1: '#FFFFFF', codigo2: '#820000', valor: 'Blanco + Vinotinto' },
{ tipo: 'COLOR', codigo1: '#820000', codigo2: '#FFFFFF', valor: 'Vinotinto + Blanco' },
{ tipo: 'COLOR', codigo1: '#FFFFFF', codigo2: '#FF0000', valor: 'Blanco + Rojo' },
{ tipo: 'COLOR', codigo1: '#FF0000', codigo2: '#FFFFFF', valor: 'Rojo + Blanco' },
{ tipo: 'COLOR', codigo1: '#FFFFFF', codigo2: '#6B8E23', valor: 'Blanco + Verde Seco' },
{ tipo: 'COLOR', codigo1: '#6B8E23', codigo2: '#FFFFFF', valor: 'Verde Seco + Blanco' },
{ tipo: 'COLOR', codigo1: '#FFFFFF', codigo2: '#4B3621', valor: 'Blanco + Café' },
{ tipo: 'COLOR', codigo1: '#4B3621', codigo2: '#FFFFFF', valor: 'Café + Blanco' },

{ tipo: 'TALLA', codigo1: '00', valor: 'Unica' },
{ tipo: 'TALLA', codigo1: '01', valor: 'S' },
{ tipo: 'TALLA', codigo1: '02', valor: 'M' },
{ tipo: 'TALLA', codigo1: '03', valor: 'L' },
{ tipo: 'TALLA', codigo1: '04', valor: 'X' },
 ]

 export default nombresData;